SuikaEnv-v0:
  # algo: dqn
  policy: 'MlpPolicy'
  # --- Hardware Saturation Settings ---
  n_timesteps: !!float 2e7      # 20 million timesteps for real training
  n_envs: 48                    # 9800X3D can handle 32+ physics threads easily
  buffer_size: 1000000          # 1M transitions (DQN needs a large memory)
  batch_size: 8192              # 5090 needs huge batches to maintain high TFLOPS
  learning_starts: 100000       # Collect initial data before hitting the GPU
  train_freq: 32                 # Update every 4 steps
  gradient_steps: 4            # Do 16 updates per train_freq to keep GPU busy
  
  # --- Algorithm Hyperparameters ---
  learning_rate: !!float 5e-5   # Slightly higher to compensate for huge batch size
  gamma: 0.95                   
  exploration_fraction: 0.2     # Explore for the first 10% of training
  exploration_initial_eps: 0.5
  exploration_final_eps: 0.05
  target_update_interval: 1  # How often to sync the "target" network
  tau: 0.005                    # SBX uses Polyak averaging for smoother updates
  
  # --- Brain Capacity ---
  policy_kwargs: "dict(net_arch=[1024, 1024, 736, 448])"

  callback: 'rl_env.callbacks.GameScoreCallback'

  env_kwargs:
    spatial_features: false
    clustering: false
    # debug: true